catch {
	this_function_does_not_exist;
} [VariableError "e"] {
    print "oops";
    e.print_stack;
};
